spring:
  profiles:
    active: dev, kafka, meilisearch, rabbitmq
    include: secret
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test_db;MODE=MYSQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false
  threads:
    virtual:
      enabled: true

server:
  port: 8080

logging:
  level:
    com.surl.first : debug
    org.hibernate.sql : debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  dev:
    domain: localhost
    frontUrl: "http://${custom.dev.domain}:3000"
    backUrl: "http://${custom.dev.domain}:${server.port}"
